services:
  bot:
    build:
      context: ./bot-ukyo
      dockerfile: Dockerfile
    env_file: ./bot-ukyo/.envp
    volumes:
      - ~/.config/ukyo-bot:/root/.config/ukyo-bot
    depends_on:
      - db
    networks:
      - bot_network

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    env_file: ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - bot_network

  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=exporter:exporter_password@(db:3306)/
    depends_on:
      - db
    networks:
      - bot_network

volumes:
  mysql_data:

networks:
  bot_network:
    driver: bridge
