services:
  bot:
    build:
      context: ./bot-ukyo
      dockerfile: Dockerfile
    env_file: ./bot-ukyo/.envp
    volumes:
      - ~/.config/ukyo-bot:/root/.config/ukyo-bot
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - network

  db:
    image: container-registry.oracle.com/mysql/community-server:9.0
    platform: linux/amd64
    env_file: ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/init_scripts/:/docker-entrypoint-initdb.d/
    restart: on-failure
    networks:
      - network
      - grafana_monitoring

volumes:
  mysql_data:

networks:
  network:
    driver: bridge
  grafana_monitoring:
    external: true
