//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    #[sea_orm(unique)]
    pub discord_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::boot::Entity")]
    Boot,
}

impl Related<super::boot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
