on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect
        run: ssh github@${{ secrets.SSH_HOST }}
      - name: pull
        run: cd /home/github/bot && git checkout main && git pull
      - name: stop and run
        run: pkill -f run.sh && ./run.sh
      - name: log out
        run: exit
      - name: cleanup
        run: rm -rf ~/.ssh
